/////////////////////////////////////////////////////////////////////////
// Javascript file generated by ctc2html v2.5
// Copyright (c) 2006-2008 Testwell Oy
/////////////////////////////////////////////////////////////////////////
target=location.hash;
function load(){
if(target=="#a1"){
parent.index.location="indexC.html#a1";
parent.profile.location="indexD1.html";
}
}
function load2(){
if(target=="#ad1"){
parent.index2.location="indexH.html#ad1";
parent.functions.location="indexB1.html";
}
}
